# nlp/metadata.py
#
# Describes every table in the DuckDB analytics database.
# Each chunk is embedded into ChromaDB and retrieved at query time
# to give Gemini accurate schema context.
#
# GROUND TRUTH column names verified from DuckDB DESCRIBE output.
# Last verified: 2026-03-20

METADATA: list[dict] = [


    # ──────────────────────────────────────────────────────────────────
    # CRITICAL NAMING RULES — embedded as a limitation so it is always
    # retrievable for any query touching counts or durations
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "limitation_column_naming",
        "type": "limitation",
        "tables": [],
        "text": """
CRITICAL: Column naming differs between monthly_chart and all other tables.

monthly_chart uses "Total *" names:
    "Total Uploaded"    BIGINT   ← NOT "Uploaded Count"
    "Total Created"     BIGINT   ← NOT "Created Count"
    "Total Published"   BIGINT   ← NOT "Published Count"

ALL other tables (combined_data_*, client_1_combined_data_*) use "* Count" names:
    "Uploaded Count"    BIGINT
    "Created Count"     BIGINT
    "Published Count"   BIGINT

WRONG:  SELECT "Uploaded Count" FROM monthly_chart;         ← returns error
RIGHT:  SELECT "Total Uploaded" FROM monthly_chart;         ← correct

Duration columns in combined_data_* and client_1_combined_data_* tables
include "(hh:mm:ss)" in their name:
    "Uploaded Duration (hh:mm:ss)_raw"    VARCHAR
    "Uploaded Duration (hh:mm:ss)_secs"   BIGINT
    "Created Duration (hh:mm:ss)_raw"     VARCHAR
    "Created Duration (hh:mm:ss)_secs"    BIGINT
    "Published Duration (hh:mm:ss)_raw"   VARCHAR
    "Published Duration (hh:mm:ss)_secs"  BIGINT

WRONG:  "Uploaded Duration_raw"           ← missing (hh:mm:ss)
RIGHT:  "Uploaded Duration (hh:mm:ss)_raw"

Duration columns in month_wise_duration do NOT have (hh:mm:ss):
    "Total Uploaded Duration_raw"    VARCHAR
    "Total Uploaded Duration_secs"   BIGINT
    "Total Created Duration_raw"     VARCHAR
    "Total Created Duration_secs"    BIGINT
    "Total Published Duration_raw"   VARCHAR
    "Total Published Duration_secs"  BIGINT
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # MONTHLY CHART
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_monthly_chart",
        "type": "table",
        "tables": ["monthly_chart"],
        "text": """
Table: monthly_chart
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Monthly aggregated production counts across the entire platform.
    One row per calendar month. Use for all time-series trend analysis.
    CAN be joined with month_wise_duration on the "Month" column.

IMPORTANT — this table uses "Total *" column names, NOT "* Count":
    "Total Uploaded"    BIGINT   ← use this, NOT "Uploaded Count"
    "Total Created"     BIGINT   ← use this, NOT "Created Count"
    "Total Published"   BIGINT   ← use this, NOT "Published Count"

Columns:
    - Month              (VARCHAR): Month label in 'Mon, YYYY' format.
                                    e.g. 'Jan, 2026', 'Mar, 2025'.
                                    Always use this exact format in WHERE clauses.
    - Total Uploaded     (BIGINT):  Source videos uploaded that month.
    - Total Created      (BIGINT):  Output videos generated by Frammer that month.
    - Total Published    (BIGINT):  Output videos published to a platform that month.

Example:
    SELECT "Month", "Total Uploaded", "Total Created", "Total Published"
    FROM monthly_chart
    ORDER BY STRPTIME("Month", '%b, %Y');

Use this table to answer:
    "What is the monthly upload/creation/publication trend?"
    "Which month had the highest number of uploads?"
    "How many videos were published in February 2026?"
    "What is the total published count across all months?"
    "What is the publish rate or creation multiplier by month?"
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # MONTH WISE DURATION
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_month_wise_duration",
        "type": "table",
        "tables": ["month_wise_duration"],
        "text": """
Table: month_wise_duration
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Monthly aggregated duration data. One row per calendar month.
    Use for all questions involving hours, minutes, or content duration.
    CAN be joined with monthly_chart on "Month".

NOTE: Duration columns here do NOT have "(hh:mm:ss)" in their name.
    "Total Uploaded Duration_raw"    VARCHAR   ← display
    "Total Uploaded Duration_secs"   BIGINT    ← use for math
    "Total Created Duration_raw"     VARCHAR
    "Total Created Duration_secs"    BIGINT
    "Total Published Duration_raw"   VARCHAR
    "Total Published Duration_secs"  BIGINT

Columns:
    - Month                          (VARCHAR): 'Mon, YYYY' format — same as monthly_chart.
    - Total Uploaded Duration_raw    (VARCHAR): Upload duration as hh:mm:ss display string.
    - Total Uploaded Duration_secs   (BIGINT):  Upload duration in seconds. Use for math.
    - Total Created Duration_raw     (VARCHAR): Creation duration as hh:mm:ss display string.
    - Total Created Duration_secs    (BIGINT):  Creation duration in seconds. Use for math.
    - Total Published Duration_raw   (VARCHAR): Published duration as hh:mm:ss display string.
    - Total Published Duration_secs  (BIGINT):  Published duration in seconds. Use for math.

Duration rules:
    - Always use _secs columns for ORDER BY, SUM, AVG, and arithmetic.
    - Always use _raw columns in SELECT for human-readable output.
    - To convert _secs to hours: ROUND(col / 3600.0, 2)
    - To convert _secs to minutes: ROUND(col / 60.0, 2)

Use this table to answer:
    "How many hours of content were uploaded each month?"
    "Which month had the longest published duration?"
    "What is the duration compression ratio by month?"
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # CHANNEL WISE PUBLISHING
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_channel_wise_publishing",
        "type": "table",
        "tables": ["channel_wise_publishing"],
        "text": """
Table: channel_wise_publishing
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Publishing counts per channel broken down by platform.
    WIDE FORMAT — one row per channel, one column per platform.
    There is NO single "Total Published" column — SUM platform columns.

Columns:
    - Channel    (VARCHAR): Channel identifier code e.g. 'A', 'D', 'G'.
    - Facebook   (BIGINT):  Videos published to Facebook.
    - Instagram  (BIGINT):  Videos published to Instagram.
    - Linkedin   (BIGINT):  Videos published to LinkedIn.
    - Reels      (BIGINT):  Videos published as Reels.
    - Shorts     (BIGINT):  Videos published as YouTube Shorts.
    - X          (BIGINT):  Videos published to X (Twitter).
    - Youtube    (BIGINT):  Videos published to YouTube.
    - Threads    (BIGINT):  Videos published to Threads.

To get total published across ALL platforms per channel:
    SELECT "Channel",
           "Facebook" + "Instagram" + "Linkedin" + "Reels" + "Shorts"
           + "X" + "Youtube" + "Threads" AS total_published
    FROM channel_wise_publishing;

To query by platform, use UNPIVOT:
    SELECT "Channel", platform, published
    FROM channel_wise_publishing
    UNPIVOT (published FOR platform IN (
        "Facebook", "Instagram", "Linkedin", "Reels",
        "Shorts", "X", "Youtube", "Threads"
    ));

Use this table to answer:
    "Which channel published the most videos?"
    "How many videos did channel D publish to YouTube?"
    "Which platform does each channel use most?"
    "Show publishing breakdown by channel and platform."
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # CHANNEL WISE PUBLISHING DURATION
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_channel_wise_publishing_duration",
        "type": "table",
        "tables": ["channel_wise_publishing_duration"],
        "text": """
Table: channel_wise_publishing_duration
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Published duration per channel broken down by platform.
    WIDE FORMAT — one row per channel, two columns per platform (_raw, _secs).
    NOTE: Duration columns here use "Platform Duration_raw/_secs" naming —
    no "(hh:mm:ss)" in the column name.

Columns:
    - Channel                 (VARCHAR)
    - Facebook Duration_raw   (VARCHAR):  hh:mm:ss display
    - Facebook Duration_secs  (BIGINT):   seconds — use for math
    - Instagram Duration_raw  (VARCHAR)
    - Instagram Duration_secs (BIGINT)
    - Linkedin Duration_raw   (VARCHAR)
    - Linkedin Duration_secs  (BIGINT)
    - Reels Duration_raw      (VARCHAR)
    - Reels Duration_secs     (BIGINT)
    - Shorts Duration_raw     (VARCHAR)
    - Shorts Duration_secs    (BIGINT)
    - X Duration_raw          (VARCHAR)
    - X Duration_secs         (BIGINT)
    - Youtube Duration_raw    (VARCHAR)
    - Youtube Duration_secs   (BIGINT)
    - Threads Duration_raw    (VARCHAR)
    - Threads Duration_secs   (BIGINT)

Duration rules:
    - Always use _secs columns for ORDER BY, SUM, AVG, and arithmetic.
    - Always use _raw columns in SELECT for human-readable output.
    - To convert _secs to hours: ROUND(col / 3600.0, 2)

Use this table to answer:
    "How many hours did channel A publish to YouTube?"
    "Which channel has the longest total published duration?"
    "Which platform has the most published duration overall?"
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # CLIENT 1 COMBINED DATA
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_client_1_combined",
        "type": "table",
        "tables": ["client_1_combined_data2025_3_1_2026_2_28"],
        "text": """
Table: client_1_combined_data2025_3_1_2026_2_28
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Top-level production summary broken down by Channel.
    One row per channel. Use for overall channel-level comparisons.

Columns:
    - Channel                                (VARCHAR)
    - Uploaded Count                         (BIGINT)
    - Created Count                          (BIGINT)
    - Published Count                        (BIGINT)
    - Uploaded Duration (hh:mm:ss)_raw       (VARCHAR): hh:mm:ss display
    - Uploaded Duration (hh:mm:ss)_secs      (BIGINT):  use for math
    - Created Duration (hh:mm:ss)_raw        (VARCHAR)
    - Created Duration (hh:mm:ss)_secs       (BIGINT)
    - Published Duration (hh:mm:ss)_raw      (VARCHAR)
    - Published Duration (hh:mm:ss)_secs     (BIGINT)

IMPORTANT: Duration columns include "(hh:mm:ss)" in the name.
    RIGHT: "Uploaded Duration (hh:mm:ss)_secs"
    WRONG: "Uploaded Duration_secs"

Use this table to answer:
    "Give me an overall production summary per channel."
    "Which channel uploaded the most content?"
    "What is the creation multiplier per channel?"
    "Which channel has the highest publish rate?"
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # COMBINED BY USER
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_combined_by_user",
        "type": "table",
        "tables": ["combined_data2025_3_1_2026_2_28_by_user"],
        "text": """
Table: combined_data2025_3_1_2026_2_28_by_user
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Total production activity broken down by User.
    One row per user. Best table for user leaderboards.

Columns:
    - User                                   (VARCHAR): User display name. NOT "Uploaded By".
    - Uploaded Count                         (BIGINT)
    - Created Count                          (BIGINT)
    - Published Count                        (BIGINT)
    - Uploaded Duration (hh:mm:ss)_raw       (VARCHAR)
    - Uploaded Duration (hh:mm:ss)_secs      (BIGINT)
    - Created Duration (hh:mm:ss)_raw        (VARCHAR)
    - Created Duration (hh:mm:ss)_secs       (BIGINT)
    - Published Duration (hh:mm:ss)_raw      (VARCHAR)
    - Published Duration (hh:mm:ss)_secs     (BIGINT)

IMPORTANT: Duration columns include "(hh:mm:ss)" in the name.
    RIGHT: "Uploaded Duration (hh:mm:ss)_secs"
    WRONG: "Uploaded Duration_secs"

Use this table to answer:
    "Which user uploaded the most videos?"
    "Show me a leaderboard of all users by upload count."
    "What is each user's publish rate?"
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # COMBINED BY CHANNEL AND USER
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_combined_by_channel_and_user",
        "type": "table",
        "tables": ["combined_data2025_3_1_2026_2_28_by_channel_and_user"],
        "text": """
Table: combined_data2025_3_1_2026_2_28_by_channel_and_user
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Activity broken down by both Channel AND User.
    One row per unique Channel × User combination.
    Use for per-channel user rankings or specific user-channel queries.

Columns:
    - Channel                                (VARCHAR)
    - User                                   (VARCHAR)
    - Uploaded Count                         (BIGINT)
    - Created Count                          (BIGINT)
    - Published Count                        (BIGINT)
    - Uploaded Duration (hh:mm:ss)_raw       (VARCHAR)
    - Uploaded Duration (hh:mm:ss)_secs      (BIGINT)
    - Created Duration (hh:mm:ss)_raw        (VARCHAR)
    - Created Duration (hh:mm:ss)_secs       (BIGINT)
    - Published Duration (hh:mm:ss)_raw      (VARCHAR)
    - Published Duration (hh:mm:ss)_secs     (BIGINT)

IMPORTANT: Duration columns include "(hh:mm:ss)" in the name.

Use this table to answer:
    "Who is the top uploading user within each channel?"
    "Show all user activity within channel A."
    "Which channel-user pair has the highest creation volume?"
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # COMBINED BY INPUT TYPE
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_combined_by_input_type",
        "type": "table",
        "tables": ["combined_data2025_3_1_2026_2_28_by_input_type"],
        "text": """
Table: combined_data2025_3_1_2026_2_28_by_input_type
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Total production activity broken down by Input Type.
    One row per input type.

Columns:
    - Input Type                             (VARCHAR)
    - Uploaded Count                         (BIGINT)
    - Created Count                          (BIGINT)
    - Published Count                        (BIGINT)
    - Uploaded Duration (hh:mm:ss)_raw       (VARCHAR)
    - Uploaded Duration (hh:mm:ss)_secs      (BIGINT)
    - Created Duration (hh:mm:ss)_raw        (VARCHAR)
    - Created Duration (hh:mm:ss)_secs       (BIGINT)
    - Published Duration (hh:mm:ss)_raw      (VARCHAR)
    - Published Duration (hh:mm:ss)_secs     (BIGINT)

IMPORTANT: Duration columns include "(hh:mm:ss)" in the name.

Use this table to answer:
    "Which type of source content is processed most?"
    "What is the publish rate for each input type?"
    "Which input type generates the most output videos?"
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # COMBINED BY OUTPUT TYPE
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_combined_by_output_type",
        "type": "table",
        "tables": ["combined_data2025_3_1_2026_2_28_by_output_type"],
        "text": """
Table: combined_data2025_3_1_2026_2_28_by_output_type
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Total production activity broken down by Output Type.
    One row per output type.

Columns:
    - Output Type                            (VARCHAR)
    - Uploaded Count                         (BIGINT)
    - Created Count                          (BIGINT)
    - Published Count                        (BIGINT)
    - Uploaded Duration (hh:mm:ss)_raw       (VARCHAR)
    - Uploaded Duration (hh:mm:ss)_secs      (BIGINT)
    - Created Duration (hh:mm:ss)_raw        (VARCHAR)
    - Created Duration (hh:mm:ss)_secs       (BIGINT)
    - Published Duration (hh:mm:ss)_raw      (VARCHAR)
    - Published Duration (hh:mm:ss)_secs     (BIGINT)

IMPORTANT: Duration columns include "(hh:mm:ss)" in the name.

Use this table to answer:
    "Which output type does Frammer produce most?"
    "Which output type has the highest publish rate?"
    "Which output type has the longest average created duration?"
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # COMBINED BY LANGUAGE
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_combined_by_language",
        "type": "table",
        "tables": ["combined_data2025_3_1_2026_2_28_by_language"],
        "text": """
Table: combined_data2025_3_1_2026_2_28_by_language
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Total production activity broken down by Language.
    One row per language.

Columns:
    - Language                               (VARCHAR): Language code e.g. 'en', 'hi', 'es'.
    - Uploaded Count                         (BIGINT)
    - Created Count                          (BIGINT)
    - Published Count                        (BIGINT)
    - Uploaded Duration (hh:mm:ss)_raw       (VARCHAR)
    - Uploaded Duration (hh:mm:ss)_secs      (BIGINT)
    - Created Duration (hh:mm:ss)_raw        (VARCHAR)
    - Created Duration (hh:mm:ss)_secs       (BIGINT)
    - Published Duration (hh:mm:ss)_raw      (VARCHAR)
    - Published Duration (hh:mm:ss)_secs     (BIGINT)

IMPORTANT: Duration columns include "(hh:mm:ss)" in the name.

Use this table to answer:
    "Which language has the most uploaded videos?"
    "What is the publish rate by language?"
    "Which language has the longest total uploaded duration?"
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # VIDEO LIST
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_video_list",
        "type": "table",
        "tables": ["video_list"],
        "text": """
Table: video_list
Layer: Individual Video Records (row per video — NOT pre-aggregated)
Description:
    Raw video-level data. One row per individual video.
    Use for individual video lookups, headline search, URL queries,
    or video-level filtering. For aggregated counts prefer flat summary tables.

Columns (all lowercase, no spaces — no quoting needed):
    - video_id           (BIGINT):    Unique video identifier.
    - headline           (VARCHAR):   Video title or headline.
    - source             (VARCHAR):   Source URL or reference.
    - published          (BOOLEAN):   TRUE if published, FALSE if not.
    - team_name          (VARCHAR):   Always 'Unknown' — team analysis not possible.
    - input_type         (VARCHAR):   Source content type.
    - uploaded_by        (VARCHAR):   Name of the uploading user.
    - published_platform (VARCHAR):   Platform published to (NULL if unpublished).
    - published_url      (VARCHAR):   Published URL (NULL if unpublished).
    - ingested_at        (TIMESTAMP): When this row was loaded into the database.

Notes:
    - team_name is always 'Unknown' — team-level analysis is not possible.
    - Filter published videos:   WHERE published = TRUE
    - Filter unpublished videos: WHERE published = FALSE

Use this table to answer:
    "Show me the 10 most recently ingested videos."
    "List all videos published to YouTube."
    "Find videos with 'budget' in the headline."
    "What percentage of video records have no valid team attribution?"
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # RELATIONSHIPS
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "relationship_monthly_join",
        "type": "relationship",
        "tables": ["monthly_chart", "month_wise_duration"],
        "text": """
Relationship: monthly_chart ↔ month_wise_duration
Join column: "Month" (VARCHAR, 'Mon, YYYY' format)
Type: One-to-one per month

This is the ONLY allowed join between flat summary tables.

COLUMN NAMES IN THIS JOIN — use exactly as shown:
    From monthly_chart:       "Total Uploaded", "Total Created", "Total Published"
    From month_wise_duration: "Total Uploaded Duration_secs", "Total Created Duration_secs"
                              "Total Published Duration_secs" (and _raw variants)

Example SQL:
    SELECT mc."Month",
           mc."Total Uploaded",
           mc."Total Created",
           mc."Total Published",
           mwd."Total Uploaded Duration_raw",
           ROUND(mwd."Total Uploaded Duration_secs" / 3600.0, 2) AS uploaded_hours,
           ROUND(mwd."Total Created Duration_secs" / 3600.0, 2)  AS created_hours,
           ROUND(mwd."Total Published Duration_secs" / 3600.0, 2) AS published_hours
    FROM monthly_chart mc
    LEFT JOIN month_wise_duration mwd ON mc."Month" = mwd."Month"
    ORDER BY STRPTIME(mc."Month", '%b, %Y');
"""
    },


    # ──────────────────────────────────────────────────────────────────
    # LIMITATIONS
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "limitation_no_joins",
        "type": "limitation",
        "tables": [],
        "text": """
Limitation: Flat summary tables cannot be joined to each other.

Independent tables (query separately — no shared join key):
    - channel_wise_publishing
    - channel_wise_publishing_duration
    - client_1_combined_data2025_3_1_2026_2_28
    - combined_data2025_3_1_2026_2_28_by_user
    - combined_data2025_3_1_2026_2_28_by_channel_and_user
    - combined_data2025_3_1_2026_2_28_by_input_type
    - combined_data2025_3_1_2026_2_28_by_output_type
    - combined_data2025_3_1_2026_2_28_by_language

ONLY EXCEPTION: monthly_chart ↔ month_wise_duration on "Month".
"""
    },

    {
        "id": "limitation_date_granularity",
        "type": "limitation",
        "tables": [],
        "text": """
Limitation: No sub-monthly date filtering in flat summary tables.

Flat summary tables are monthly-granularity only. No date columns exist.
Month format is strictly 'Mon, YYYY':
    WHERE "Month" = 'Jan, 2026'    ✓ correct
    WHERE "Month" = 'January 2026' ✗ returns no results
    WHERE "Month" = '2026-01'      ✗ returns no results

Dataset range: March 2025 – February 2026 only.
Any month outside this range → CANNOT_ANSWER.
"""
    },

    {
        "id": "limitation_no_team_data",
        "type": "limitation",
        "tables": ["video_list"],
        "text": """
Limitation: Team data is not available.
The team_name column in video_list contains 'Unknown' for all rows.
If a user asks about teams → CANNOT_ANSWER: Team data is not available.
"""
    },

    {
        "id": "limitation_no_financial_data",
        "type": "limitation",
        "tables": [],
        "text": """
Limitation: No financial, revenue, or cost data exists.
If a user asks about money, revenue, cost, or ROI → CANNOT_ANSWER.
"""
    },

]