# nlp/metadata.py
#
# Describes every table in the DuckDB analytics database.
# Each chunk is embedded into ChromaDB and retrieved at query time
# to give Gemini accurate schema context.
#
# GROUND TRUTH column names verified from DuckDB DESCRIBE output.
# Last verified: 2026-03-13

METADATA: list[dict] = [

    # ──────────────────────────────────────────────────────────────────
    # MONTHLY CHART
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_monthly_chart",
        "type": "table",
        "tables": ["monthly_chart"],
        "text": """
Table: monthly_chart
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Monthly aggregated production counts across the entire platform.
    One row per calendar month. Use for all time-series trend analysis.
    CAN be joined with month_wise_duration on the "Month" column —
    this is the ONE allowed join between flat summary tables.

Columns:
    - Month              (VARCHAR): Month label in 'Mon, YYYY' format.
                                    e.g. 'Jan, 2026', 'Mar, 2025'.
                                    Always use this exact format in WHERE clauses.
    - Total Uploaded     (BIGINT):  Source videos uploaded that month.
    - Total Created      (BIGINT):  Output videos generated by Frammer that month.
    - Total Published    (BIGINT):  Output videos published to a platform that month.

Use this table to answer:
    "What is the monthly upload/creation/publication trend?"
    "Which month had the highest number of uploads?"
    "How many videos were published in February 2026?"
    "What is the total published count across all months?"
    "What is the publish rate or creation multiplier by month?"
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # MONTH WISE DURATION
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_month_wise_duration",
        "type": "table",
        "tables": ["month_wise_duration"],
        "text": """
Table: month_wise_duration
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Monthly aggregated duration data. One row per calendar month.
    Use for all questions involving hours, minutes, or content duration.
    CAN be joined with monthly_chart on "Month" — the ONE allowed join
    between flat summary tables.

Columns:
    - Month                          (VARCHAR): 'Mon, YYYY' format — same as monthly_chart.
    - Total Uploaded Duration_raw    (VARCHAR): Upload duration as hh:mm:ss display string.
    - Total Uploaded Duration_secs   (BIGINT):  Upload duration in seconds. Use for math.
    - Total Created Duration_raw     (VARCHAR): Creation duration as hh:mm:ss display string.
    - Total Created Duration_secs    (BIGINT):  Creation duration in seconds. Use for math.
    - Total Published Duration_raw   (VARCHAR): Published duration as hh:mm:ss display string.
    - Total Published Duration_secs  (BIGINT):  Published duration in seconds. Use for math.

Duration rules:
    - Always use _secs columns for ORDER BY, SUM, AVG, and arithmetic.
    - Always use _raw columns in SELECT for human-readable output.
    - Hours in _raw can exceed 24 (e.g. '121:59:42').
    - To convert _secs to hours: ROUND(col / 3600.0, 2)
    - To convert _secs to minutes: ROUND(col / 60.0, 2)

Use this table to answer:
    "How many hours of content were uploaded each month?"
    "Which month had the longest published duration?"
    "What is the duration compression ratio by month?"
    "What is the average created video duration per month?"
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # CHANNEL WISE PUBLISHING
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_channel_wise_publishing",
        "type": "table",
        "tables": ["channel_wise_publishing"],
        "text": """
Table: channel_wise_publishing
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Publishing counts per channel broken down by platform.
    WIDE FORMAT — one row per channel, one column per platform.
    There is NO single "Total Published" column — you must SUM platform
    columns to get the total published count for a channel.

Columns:
    - Channel    (VARCHAR): Channel identifier code e.g. 'L', 'N', 'A', 'E', 'S', 'K'.
    - Facebook   (BIGINT):  Videos published to Facebook.
    - Instagram  (BIGINT):  Videos published to Instagram.
    - Linkedin   (BIGINT):  Videos published to LinkedIn.
    - Reels      (BIGINT):  Videos published as Reels.
    - Shorts     (BIGINT):  Videos published as YouTube Shorts.
    - X          (BIGINT):  Videos published to X (Twitter).
    - Youtube    (BIGINT):  Videos published to YouTube.
    - Threads    (BIGINT):  Videos published to Threads.

WIDE FORMAT rules:
    To get total published across ALL platforms for each channel:
        SELECT "Channel",
               "Facebook" + "Instagram" + "Linkedin" + "Reels" + "Shorts"
               + "X" + "Youtube" + "Threads" AS total_published
        FROM channel_wise_publishing;

    To query by platform, use UNPIVOT:
        SELECT "Channel", platform, published
        FROM channel_wise_publishing
        UNPIVOT (published FOR platform IN (
            "Facebook", "Instagram", "Linkedin", "Reels",
            "Shorts", "X", "Youtube", "Threads"
        ));

Use this table to answer:
    "Which channel published the most videos?"
    "How many videos did channel L publish to YouTube?"
    "Which platform does each channel use most?"
    "Show publishing breakdown by channel and platform."
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # CHANNEL WISE PUBLISHING DURATION
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_channel_wise_publishing_duration",
        "type": "table",
        "tables": ["channel_wise_publishing_duration"],
        "text": """
Table: channel_wise_publishing_duration
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Published duration per channel broken down by platform.
    WIDE FORMAT — one row per channel, two columns per platform (_raw and _secs).
    Use _secs columns for arithmetic, _raw for display.

Columns:
    - Channel                (VARCHAR): Channel identifier code.
    - Facebook Duration_raw  (VARCHAR): Published duration on Facebook as hh:mm:ss.
    - Facebook Duration_secs (BIGINT):  Published duration on Facebook in seconds.
    - Instagram Duration_raw (VARCHAR): Published duration on Instagram as hh:mm:ss.
    - Instagram Duration_secs(BIGINT):  Published duration on Instagram in seconds.
    - Linkedin Duration_raw  (VARCHAR): Published duration on LinkedIn as hh:mm:ss.
    - Linkedin Duration_secs (BIGINT):  Published duration on LinkedIn in seconds.
    - Reels Duration_raw     (VARCHAR): Published duration as Reels as hh:mm:ss.
    - Reels Duration_secs    (BIGINT):  Published duration as Reels in seconds.
    - Shorts Duration_raw    (VARCHAR): Published duration as Shorts as hh:mm:ss.
    - Shorts Duration_secs   (BIGINT):  Published duration as Shorts in seconds.
    - X Duration_raw         (VARCHAR): Published duration on X as hh:mm:ss.
    - X Duration_secs        (BIGINT):  Published duration on X in seconds.
    - Youtube Duration_raw   (VARCHAR): Published duration on YouTube as hh:mm:ss.
    - Youtube Duration_secs  (BIGINT):  Published duration on YouTube in seconds.
    - Threads Duration_raw   (VARCHAR): Published duration on Threads as hh:mm:ss.
    - Threads Duration_secs  (BIGINT):  Published duration on Threads in seconds.

Duration rules:
    - Always use _secs columns for ORDER BY, SUM, AVG, and arithmetic.
    - Always use _raw columns in SELECT for human-readable output.
    - To convert _secs to hours: ROUND(col / 3600.0, 2)

Use this table to answer:
    "How many hours did channel L publish to YouTube?"
    "Which channel has the longest total published duration?"
    "Which platform has the most published duration overall?"
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # CLIENT 1 COMBINED DATA
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_client_1_combined",
        "type": "table",
        "tables": ["client_1_combined_data_2025_3_1_2026_2_28"],
        "text": """
Table: client_1_combined_data_2025_3_1_2026_2_28
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Top-level production summary broken down by Channel.
    One row per channel. Use for overall channel-level comparisons.

Columns:
    - Channel                              (VARCHAR): Channel identifier code.
    - Uploaded Count                       (BIGINT):  Total source videos uploaded.
    - Created Count                        (BIGINT):  Total output videos created.
    - Published Count                      (BIGINT):  Total output videos published.
    - Uploaded Duration (hh:mm:ss)_raw     (VARCHAR): Upload duration as hh:mm:ss.
    - Uploaded Duration (hh:mm:ss)_secs    (BIGINT):  Upload duration in seconds.
    - Created Duration (hh:mm:ss)_raw      (VARCHAR): Creation duration as hh:mm:ss.
    - Created Duration (hh:mm:ss)_secs     (BIGINT):  Creation duration in seconds.
    - Published Duration (hh:mm:ss)_raw    (VARCHAR): Published duration as hh:mm:ss.
    - Published Duration (hh:mm:ss)_secs   (BIGINT):  Published duration in seconds.

Duration rules:
    - Always use _secs columns for ORDER BY, SUM, AVG, and arithmetic.
    - Always use _raw columns in SELECT for human-readable output.

Use this table to answer:
    "Give me an overall production summary per channel."
    "Which channel uploaded the most content?"
    "What is the creation multiplier per channel?"
    "Which channel has the highest publish rate?"
    "How many hours of content did each channel create?"
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # COMBINED BY USER
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_combined_by_user",
        "type": "table",
        "tables": ["combined_data_2025_3_1_2026_2_28_by_user"],
        "text": """
Table: combined_data_2025_3_1_2026_2_28_by_user
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Total production activity broken down by User.
    One row per user. Best table for user leaderboards and
    individual user productivity analysis.

Columns:
    - User                                 (VARCHAR): User's display name.
    - Uploaded Count                       (BIGINT):  Total source videos uploaded.
    - Created Count                        (BIGINT):  Total output videos created.
    - Published Count                      (BIGINT):  Total output videos published.
    - Uploaded Duration (hh:mm:ss)_raw     (VARCHAR): Upload duration as hh:mm:ss.
    - Uploaded Duration (hh:mm:ss)_secs    (BIGINT):  Upload duration in seconds.
    - Created Duration (hh:mm:ss)_raw      (VARCHAR): Creation duration as hh:mm:ss.
    - Created Duration (hh:mm:ss)_secs     (BIGINT):  Creation duration in seconds.
    - Published Duration (hh:mm:ss)_raw    (VARCHAR): Published duration as hh:mm:ss.
    - Published Duration (hh:mm:ss)_secs   (BIGINT):  Published duration in seconds.

NOTE: The user column is named "User" — NOT "Uploaded By".

Duration rules:
    - Always use _secs columns for ORDER BY, SUM, AVG, and arithmetic.
    - Always use _raw columns in SELECT for human-readable output.

Use this table to answer:
    "Which user uploaded the most videos?"
    "Show me a leaderboard of all users by upload count."
    "What is each user's publish rate?"
    "Which user has the highest creation multiplier?"
    "How many hours of content has each user uploaded?"
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # COMBINED BY CHANNEL AND USER
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_combined_by_channel_and_user",
        "type": "table",
        "tables": ["combined_data_2025_3_1_2026_2_28_by_channel_and_user"],
        "text": """
Table: combined_data_2025_3_1_2026_2_28_by_channel_and_user
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Most granular summary table. Activity broken down by both
    Channel AND User. One row per unique Channel × User combination.
    Use when a question asks about a specific user within a channel,
    or for per-channel user rankings.

Columns:
    - Channel                              (VARCHAR): Channel identifier code.
    - User                                 (VARCHAR): User's display name.
    - Uploaded Count                       (BIGINT):  Videos uploaded by this user in this channel.
    - Created Count                        (BIGINT):  Videos created for this channel by this user.
    - Published Count                      (BIGINT):  Videos published for this channel by this user.
    - Uploaded Duration (hh:mm:ss)_raw     (VARCHAR): Upload duration as hh:mm:ss.
    - Uploaded Duration (hh:mm:ss)_secs    (BIGINT):  Upload duration in seconds.
    - Created Duration (hh:mm:ss)_raw      (VARCHAR): Creation duration as hh:mm:ss.
    - Created Duration (hh:mm:ss)_secs     (BIGINT):  Creation duration in seconds.
    - Published Duration (hh:mm:ss)_raw    (VARCHAR): Published duration as hh:mm:ss.
    - Published Duration (hh:mm:ss)_secs   (BIGINT):  Published duration in seconds.

Duration rules:
    - Always use _secs columns for ORDER BY, SUM, AVG, and arithmetic.
    - Always use _raw columns in SELECT for human-readable output.

Use this table to answer:
    "Who is the top uploading user within each channel?"
    "Show all user activity within channel L."
    "Which channel-user pair has the highest creation volume?"
    "How does user X perform across different channels?"
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # COMBINED BY INPUT TYPE
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_combined_by_input_type",
        "type": "table",
        "tables": ["combined_data_2025_3_1_2026_2_28_by_input_type"],
        "text": """
Table: combined_data_2025_3_1_2026_2_28_by_input_type
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Total production activity broken down by Input Type (source content type).
    One row per input type.

Columns:
    - Input Type                           (VARCHAR): Source content type label.
    - Uploaded Count                       (BIGINT):  Total source videos uploaded.
    - Created Count                        (BIGINT):  Total output videos created.
    - Published Count                      (BIGINT):  Total output videos published.
    - Uploaded Duration (hh:mm:ss)_raw     (VARCHAR): Upload duration as hh:mm:ss.
    - Uploaded Duration (hh:mm:ss)_secs    (BIGINT):  Upload duration in seconds.
    - Created Duration (hh:mm:ss)_raw      (VARCHAR): Creation duration as hh:mm:ss.
    - Created Duration (hh:mm:ss)_secs     (BIGINT):  Creation duration in seconds.
    - Published Duration (hh:mm:ss)_raw    (VARCHAR): Published duration as hh:mm:ss.
    - Published Duration (hh:mm:ss)_secs   (BIGINT):  Published duration in seconds.

Duration rules:
    - Always use _secs columns for ORDER BY, SUM, AVG, and arithmetic.
    - Always use _raw columns in SELECT for human-readable output.

Use this table to answer:
    "Which type of source content is processed most?"
    "What is the publish rate for each input type?"
    "Which input type generates the most output videos?"
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # COMBINED BY OUTPUT TYPE
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_combined_by_output_type",
        "type": "table",
        "tables": ["combined_data_2025_3_1_2026_2_28_by_output_type"],
        "text": """
Table: combined_data_2025_3_1_2026_2_28_by_output_type
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Total production activity broken down by Output Type (the kind of
    content Frammer produces). One row per output type.

Columns:
    - Output Type                          (VARCHAR): Output content type label.
    - Uploaded Count                       (BIGINT):  Total source videos uploaded.
    - Created Count                        (BIGINT):  Total output videos created.
    - Published Count                      (BIGINT):  Total output videos published.
    - Uploaded Duration (hh:mm:ss)_raw     (VARCHAR): Upload duration as hh:mm:ss.
    - Uploaded Duration (hh:mm:ss)_secs    (BIGINT):  Upload duration in seconds.
    - Created Duration (hh:mm:ss)_raw      (VARCHAR): Creation duration as hh:mm:ss.
    - Created Duration (hh:mm:ss)_secs     (BIGINT):  Creation duration in seconds.
    - Published Duration (hh:mm:ss)_raw    (VARCHAR): Published duration as hh:mm:ss.
    - Published Duration (hh:mm:ss)_secs   (BIGINT):  Published duration in seconds.

Duration rules:
    - Always use _secs columns for ORDER BY, SUM, AVG, and arithmetic.
    - Always use _raw columns in SELECT for human-readable output.

Use this table to answer:
    "Which output type does Frammer produce most?"
    "Which output type has the highest publish rate?"
    "Which output type has the longest average created duration?"
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # COMBINED BY LANGUAGE
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_combined_by_language",
        "type": "table",
        "tables": ["combined_data_2025_3_1_2026_2_28_by_language"],
        "text": """
Table: combined_data_2025_3_1_2026_2_28_by_language
Layer: Flat Summary Table (pre-aggregated, no joins needed)
Description:
    Total production activity broken down by Language.
    One row per language.

Columns:
    - Language                             (VARCHAR): Language of source content.
    - Uploaded Count                       (BIGINT):  Total source videos uploaded.
    - Created Count                        (BIGINT):  Total output videos created.
    - Published Count                      (BIGINT):  Total output videos published.
    - Uploaded Duration (hh:mm:ss)_raw     (VARCHAR): Upload duration as hh:mm:ss.
    - Uploaded Duration (hh:mm:ss)_secs    (BIGINT):  Upload duration in seconds.
    - Created Duration (hh:mm:ss)_raw      (VARCHAR): Creation duration as hh:mm:ss.
    - Created Duration (hh:mm:ss)_secs     (BIGINT):  Creation duration in seconds.
    - Published Duration (hh:mm:ss)_raw    (VARCHAR): Published duration as hh:mm:ss.
    - Published Duration (hh:mm:ss)_secs   (BIGINT):  Published duration in seconds.

Duration rules:
    - Always use _secs columns for ORDER BY, SUM, AVG, and arithmetic.
    - Always use _raw columns in SELECT for human-readable output.

Use this table to answer:
    "Which language has the most uploaded videos?"
    "What is the publish rate by language?"
    "Which language has the longest total uploaded duration?"
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # VIDEO LIST
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "table_video_list",
        "type": "table",
        "tables": ["video_list"],
        "text": """
Table: video_list
Layer: Individual Video Records (row per video — NOT pre-aggregated)
Description:
    Raw video-level data. One row per individual video. This is the
    most granular table in the database. Use when a question asks about
    individual videos, specific headlines, URLs, or video-level filtering.
    For aggregated counts and durations, prefer the flat summary tables.

Columns:
    - video_id           (BIGINT):    Unique identifier for each video.
    - headline           (VARCHAR):   Video title or headline.
    - source             (VARCHAR):   Source URL or reference of the input content.
    - published          (BOOLEAN):   TRUE if published, FALSE if not.
    - team_name          (VARCHAR):   Team that uploaded the video (currently all 'Unknown').
    - input_type         (VARCHAR):   Type of source content (e.g. speech, interview).
    - uploaded_by        (VARCHAR):   Name of the user who uploaded the video.
    - published_platform (VARCHAR):   Platform the video was published to (NULL if unpublished).
    - published_url      (VARCHAR):   URL of the published video (NULL if unpublished).
    - ingested_at        (TIMESTAMP): When this row was loaded into the database.

Important notes:
    - team_name is always 'Unknown' — team-level analysis is not possible.
    - published_platform and published_url are NULL for unpublished videos.
    - To count published videos: WHERE published = TRUE
    - To count unpublished videos: WHERE published = FALSE
    - All column names are lowercase with underscores (no spaces, no quotes needed).

Use this table to answer:
    "Show me the 10 most recently ingested videos."
    "List all videos published to YouTube."
    "How many individual videos has user X uploaded?"
    "Which videos were published to Instagram?"
    "Find videos with 'budget' in the headline."
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # RELATIONSHIPS
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "relationship_monthly_join",
        "type": "relationship",
        "tables": ["monthly_chart", "month_wise_duration"],
        "text": """
Relationship: monthly_chart ↔ month_wise_duration
Join column: "Month" (VARCHAR, 'Mon, YYYY' format)
Type: One-to-one per month

This is the ONLY allowed join between flat summary tables.
All other flat summary tables are independent and must NOT be joined.

Use when you need both count metrics AND duration metrics in the same query.

Example SQL:
    SELECT c."Month",
           c."Total Uploaded",
           c."Total Created",
           d."Total Uploaded Duration_raw",
           ROUND(d."Total Created Duration_secs" * 1.0
               / NULLIF(c."Total Created", 0) / 60.0, 2)
               AS avg_created_duration_mins
    FROM monthly_chart c
    JOIN month_wise_duration d ON c."Month" = d."Month"
    ORDER BY c."Month";
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # LIMITATIONS
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "limitation_no_joins",
        "type": "limitation",
        "tables": [],
        "text": """
Limitation: Flat summary tables cannot be joined to each other.

The following tables are all independent pre-aggregated snapshots
covering the same overall period (March 2025 – February 2026).
They share NO common join key and must be queried independently:

    - channel_wise_publishing
    - channel_wise_publishing_duration
    - client_1_combined_data_2025_3_1_2026_2_28
    - combined_data_2025_3_1_2026_2_28_by_user
    - combined_data_2025_3_1_2026_2_28_by_channel_and_user
    - combined_data_2025_3_1_2026_2_28_by_input_type
    - combined_data_2025_3_1_2026_2_28_by_output_type
    - combined_data_2025_3_1_2026_2_28_by_language

ONLY EXCEPTION: monthly_chart and month_wise_duration can be joined
on the "Month" column.

If a user asks a question that would require joining two of the above
tables (e.g. "which channel has the most uploads AND the highest
publish rate by platform"), query each table separately or note that
the combined view is not available.
"""
    },

    {
        "id": "limitation_date_granularity",
        "type": "limitation",
        "tables": [],
        "text": """
Limitation: No sub-monthly date filtering in flat summary tables.

The flat summary tables (monthly_chart, month_wise_duration, and all
combined_data_* tables) contain data aggregated at monthly granularity.
They do NOT have individual date or timestamp columns.

You CANNOT filter by specific dates within a month using these tables.
The only date-level filtering available is by month label.

Month format is strictly 'Mon, YYYY':
    WHERE "Month" = 'Jan, 2026'    ✓ correct
    WHERE "Month" = 'January 2026' ✗ will return no results
    WHERE "Month" = '2026-01'      ✗ will return no results

For date-level filtering, use the video_list table which has
an ingested_at TIMESTAMP column (though this reflects ingestion
time, not upload time).

Dataset date range: March 2025 – February 2026 only.
Any question about months outside this range → CANNOT_ANSWER.
"""
    },

    {
        "id": "limitation_no_team_data",
        "type": "limitation",
        "tables": ["video_list"],
        "text": """
Limitation: Team data is not available.

The team_name column in video_list contains 'Unknown' for all rows.
Team-level analysis, filtering, or ranking is not possible.

If a user asks about teams → return:
CANNOT_ANSWER: Team data is not available — all team_name values are 'Unknown'.
"""
    },

    {
        "id": "limitation_no_financial_data",
        "type": "limitation",
        "tables": [],
        "text": """
Limitation: No financial, revenue, or cost data exists.

This dataset contains only video production and publishing activity metrics.
There is no data on revenue, cost, pricing, ROI, subscriptions, or any
financial dimension whatsoever.

If a user asks about money, revenue, cost, or ROI → return:
CANNOT_ANSWER: No financial data exists in this dataset.
"""
    },

]
