# nlp/metrics.py
#
# Defines all business KPIs, formulas, and derived metrics.
# Each entry is a chunk embedded into ChromaDB.
#
# GROUND TRUTH column names (verified 2026-03-13):
#   monthly_chart:          "Total Uploaded", "Total Created", "Total Published"
#   all combined_data_*:    "Uploaded Count", "Created Count", "Published Count"
#   all combined_data_*:    "Uploaded Duration (hh:mm:ss)_secs/_raw"
#   month_wise_duration:    "Total Uploaded/Created/Published Duration_secs/_raw"
#   channel_wise_publishing: WIDE — one column per platform, NO "Total Published"
#   channel_wise_pub_dur:   "<Platform> Duration_secs/_raw" per platform
#   user column:            "User" (NOT "Uploaded By")

METRICS: list[dict] = [

    # ──────────────────────────────────────────────────────────────────
    # CORE COUNT METRICS
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "metric_total_uploaded",
        "type": "metric",
        "tables": ["monthly_chart", "client_1_combined_data_2025_3_1_2026_2_28",
                   "combined_data_2025_3_1_2026_2_28_by_user",
                   "combined_data_2025_3_1_2026_2_28_by_channel_and_user",
                   "combined_data_2025_3_1_2026_2_28_by_input_type",
                   "combined_data_2025_3_1_2026_2_28_by_output_type",
                   "combined_data_2025_3_1_2026_2_28_by_language"],
        "text": """
Metric: Total Uploaded / Uploaded Count
Definition:
    The total number of SOURCE videos uploaded into the Frammer platform
    for processing. This is the INPUT volume — raw content brought in
    before Frammer creates any outputs.

CRITICAL — Column name differs by table:
    monthly_chart ONLY:       "Total Uploaded"   (BIGINT)
    ALL other summary tables: "Uploaded Count"   (BIGINT)

Important distinction:
    Uploaded = source content going IN to Frammer.
    Created  = output content coming OUT of Frammer.
    One uploaded video can produce many created outputs.

Available at these dimensions:
    - Monthly level:        monthly_chart                              → "Total Uploaded"
    - Channel level:        client_1_combined_data_2025_3_1_2026_2_28 → "Uploaded Count"
    - User level:           combined_data_2025_3_1_2026_2_28_by_user  → "Uploaded Count"
    - Channel × User:       combined_data_..._by_channel_and_user     → "Uploaded Count"
    - Input type level:     combined_data_..._by_input_type           → "Uploaded Count"
    - Output type level:    combined_data_..._by_output_type          → "Uploaded Count"
    - Language level:       combined_data_..._by_language             → "Uploaded Count"

Example SQL (uploads by user):
    SELECT "User", "Uploaded Count"
    FROM combined_data_2025_3_1_2026_2_28_by_user
    ORDER BY "Uploaded Count" DESC;

Example SQL (total uploads by month):
    SELECT "Month", "Total Uploaded"
    FROM monthly_chart
    ORDER BY "Month";
"""
    },

    {
        "id": "metric_total_created",
        "type": "metric",
        "tables": ["monthly_chart", "client_1_combined_data_2025_3_1_2026_2_28",
                   "combined_data_2025_3_1_2026_2_28_by_user",
                   "combined_data_2025_3_1_2026_2_28_by_channel_and_user",
                   "combined_data_2025_3_1_2026_2_28_by_input_type",
                   "combined_data_2025_3_1_2026_2_28_by_output_type",
                   "combined_data_2025_3_1_2026_2_28_by_language"],
        "text": """
Metric: Total Created / Created Count
Definition:
    The total number of OUTPUT videos generated by Frammer from uploaded
    source content. This is the PRODUCTION volume.
    One uploaded video typically produces multiple created outputs.

CRITICAL — Column name differs by table:
    monthly_chart ONLY:       "Total Created"   (BIGINT)
    ALL other summary tables: "Created Count"   (BIGINT)

Key insight:
    Created >> Uploaded. Frammer generates multiple output clips per source.
    Ratio: Created / Uploaded = "Creation Multiplier".

Example SQL (creation multiplier by month — uses monthly_chart):
    SELECT "Month",
           "Total Uploaded",
           "Total Created",
           ROUND("Total Created" * 1.0 / NULLIF("Total Uploaded", 0), 2)
               AS creation_multiplier
    FROM monthly_chart
    ORDER BY "Month";

Example SQL (creation multiplier by channel — uses combined table):
    SELECT "Channel",
           "Uploaded Count",
           "Created Count",
           ROUND("Created Count" * 1.0 / NULLIF("Uploaded Count", 0), 2)
               AS creation_multiplier
    FROM client_1_combined_data_2025_3_1_2026_2_28
    ORDER BY creation_multiplier DESC;
"""
    },

    {
        "id": "metric_total_published",
        "type": "metric",
        "tables": ["monthly_chart", "channel_wise_publishing",
                   "client_1_combined_data_2025_3_1_2026_2_28",
                   "combined_data_2025_3_1_2026_2_28_by_user",
                   "combined_data_2025_3_1_2026_2_28_by_input_type",
                   "combined_data_2025_3_1_2026_2_28_by_output_type",
                   "combined_data_2025_3_1_2026_2_28_by_language"],
        "text": """
Metric: Total Published / Published Count
Definition:
    The total number of created output videos that were approved and
    published to an external platform. Final DELIVERY volume:
    Uploaded → Created → Published.

CRITICAL — Column name differs by table:
    monthly_chart ONLY:       "Total Published"   (BIGINT)
    ALL other summary tables: "Published Count"   (BIGINT)
    channel_wise_publishing:  NO single "Published Count" column — WIDE FORMAT.
                              Has one column per platform: "Facebook", "Instagram",
                              "Linkedin", "Reels", "Shorts", "X", "Youtube", "Threads".
                              To get total: SUM all platform columns.

Key insight:
    Published << Created. Not all created outputs pass editorial review.

Example SQL (total published by month):
    SELECT "Month", "Total Published"
    FROM monthly_chart
    ORDER BY "Month";

Example SQL (total published per channel across all platforms):
    SELECT "Channel",
           "Facebook" + "Instagram" + "Linkedin" + "Reels" + "Shorts"
           + "X" + "Youtube" + "Threads" AS total_published
    FROM channel_wise_publishing
    ORDER BY total_published DESC;

Example SQL (published count by user):
    SELECT "User", "Published Count"
    FROM combined_data_2025_3_1_2026_2_28_by_user
    ORDER BY "Published Count" DESC;
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # RATE METRICS
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "metric_publish_rate",
        "type": "metric",
        "tables": ["monthly_chart", "client_1_combined_data_2025_3_1_2026_2_28",
                   "combined_data_2025_3_1_2026_2_28_by_user",
                   "combined_data_2025_3_1_2026_2_28_by_input_type",
                   "combined_data_2025_3_1_2026_2_28_by_output_type",
                   "combined_data_2025_3_1_2026_2_28_by_language",
                   "combined_data_2025_3_1_2026_2_28_by_channel_and_user"],
        "text": """
Metric: Publish Rate
Definition:
    The percentage of CREATED output videos that were actually published.
    Measures editorial output efficiency.

Formula:
    Publish Rate (%) = (Published / Created) * 100

CRITICAL — Use correct column names per table:
    monthly_chart:          "Total Published" / "Total Created"
    ALL other summary tables: "Published Count" / "Created Count"

Always wrap denominator in NULLIF(..., 0) to avoid division by zero.

Interpretation:
    > 50%: Most created content is being published.
    < 10%: Most content is filtered out before publishing.
      0%:  Content was created but nothing published that period.

Example SQL (publish rate by month):
    SELECT "Month",
           "Total Created",
           "Total Published",
           ROUND("Total Published" * 100.0 / NULLIF("Total Created", 0), 2)
               AS publish_rate_pct
    FROM monthly_chart
    ORDER BY "Month";

Example SQL (publish rate by user):
    SELECT "User",
           "Created Count",
           "Published Count",
           ROUND("Published Count" * 100.0 / NULLIF("Created Count", 0), 2)
               AS publish_rate_pct
    FROM combined_data_2025_3_1_2026_2_28_by_user
    ORDER BY publish_rate_pct DESC;

Example SQL (publish rate by channel):
    SELECT "Channel",
           "Created Count",
           "Published Count",
           ROUND("Published Count" * 100.0 / NULLIF("Created Count", 0), 2)
               AS publish_rate_pct
    FROM client_1_combined_data_2025_3_1_2026_2_28
    ORDER BY publish_rate_pct DESC;

Example SQL (publish rate by input type):
    SELECT "Input Type",
           "Created Count",
           "Published Count",
           ROUND("Published Count" * 100.0 / NULLIF("Created Count", 0), 2)
               AS publish_rate_pct
    FROM combined_data_2025_3_1_2026_2_28_by_input_type
    ORDER BY publish_rate_pct DESC;
"""
    },

    {
        "id": "metric_creation_multiplier",
        "type": "metric",
        "tables": ["monthly_chart", "client_1_combined_data_2025_3_1_2026_2_28",
                   "combined_data_2025_3_1_2026_2_28_by_user",
                   "combined_data_2025_3_1_2026_2_28_by_channel_and_user"],
        "text": """
Metric: Creation Multiplier (also called Output Ratio)
Definition:
    The number of output videos Frammer generates per source video uploaded.
    Measures platform productivity.

Formula:
    Creation Multiplier = Created / Uploaded

CRITICAL — Use correct column names per table:
    monthly_chart:            "Total Created" / "Total Uploaded"
    ALL other summary tables: "Created Count" / "Uploaded Count"

Interpretation:
    5x = Frammer generates 5 output clips per source video.
    Higher = more productive. < 1 would be unusual.

Example SQL (by month):
    SELECT "Month",
           ROUND("Total Created" * 1.0 / NULLIF("Total Uploaded", 0), 2)
               AS creation_multiplier
    FROM monthly_chart
    ORDER BY creation_multiplier DESC;

Example SQL (by channel):
    SELECT "Channel",
           "Uploaded Count",
           "Created Count",
           ROUND("Created Count" * 1.0 / NULLIF("Uploaded Count", 0), 2)
               AS creation_multiplier
    FROM client_1_combined_data_2025_3_1_2026_2_28
    ORDER BY creation_multiplier DESC;

Example SQL (by user):
    SELECT "User",
           "Uploaded Count",
           "Created Count",
           ROUND("Created Count" * 1.0 / NULLIF("Uploaded Count", 0), 2)
               AS creation_multiplier
    FROM combined_data_2025_3_1_2026_2_28_by_user
    ORDER BY creation_multiplier DESC;
"""
    },

    {
        "id": "metric_upload_to_publish_rate",
        "type": "metric",
        "tables": ["monthly_chart", "client_1_combined_data_2025_3_1_2026_2_28",
                   "combined_data_2025_3_1_2026_2_28_by_user"],
        "text": """
Metric: Upload-to-Publish Rate (End-to-End Pipeline Efficiency)
Definition:
    The percentage of uploaded source videos that result in at least one
    published output. Measures full pipeline efficiency.

Formula:
    Upload-to-Publish Rate (%) = (Published / Uploaded) * 100

Distinction from Publish Rate:
    Publish Rate           = Published / Created   (editorial efficiency)
    Upload-to-Publish Rate = Published / Uploaded  (end-to-end efficiency)

Note: Can exceed 100% since one upload can produce many published outputs.

CRITICAL — Use correct column names per table:
    monthly_chart:            "Total Published" / "Total Uploaded"
    ALL other summary tables: "Published Count" / "Uploaded Count"

Example SQL (by month):
    SELECT "Month",
           ROUND("Total Published" * 100.0 / NULLIF("Total Uploaded", 0), 2)
               AS upload_to_publish_rate_pct
    FROM monthly_chart
    ORDER BY "Month";

Example SQL (by user):
    SELECT "User",
           "Uploaded Count",
           "Published Count",
           ROUND("Published Count" * 100.0 / NULLIF("Uploaded Count", 0), 2)
               AS upload_to_publish_rate_pct
    FROM combined_data_2025_3_1_2026_2_28_by_user
    ORDER BY upload_to_publish_rate_pct DESC;
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # DURATION METRICS
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "metric_duration_columns",
        "type": "metric",
        "tables": ["month_wise_duration", "channel_wise_publishing_duration",
                   "client_1_combined_data_2025_3_1_2026_2_28",
                   "combined_data_2025_3_1_2026_2_28_by_user",
                   "combined_data_2025_3_1_2026_2_28_by_channel_and_user",
                   "combined_data_2025_3_1_2026_2_28_by_input_type",
                   "combined_data_2025_3_1_2026_2_28_by_output_type",
                   "combined_data_2025_3_1_2026_2_28_by_language"],
        "text": """
Duration Columns — Complete Reference by Table:

All duration data is stored as TWO paired columns per duration type:
    _raw   (VARCHAR): Human-readable hh:mm:ss string. Use only in SELECT for display.
    _secs  (BIGINT):  Duration in seconds. Use for ALL math, ORDER BY, SUM, AVG.

Hours in _raw CAN exceed 24 (e.g. '121:59:42' = 121 hours).
To convert _secs to hours: ROUND(col / 3600.0, 2)
To convert _secs to minutes: ROUND(col / 60.0, 2)

Column names by table:

    month_wise_duration:
        "Total Uploaded Duration_raw"    / "Total Uploaded Duration_secs"
        "Total Created Duration_raw"     / "Total Created Duration_secs"
        "Total Published Duration_raw"   / "Total Published Duration_secs"

    client_1_combined_data_2025_3_1_2026_2_28
    combined_data_..._by_user
    combined_data_..._by_channel_and_user
    combined_data_..._by_input_type
    combined_data_..._by_output_type
    combined_data_..._by_language:
        "Uploaded Duration (hh:mm:ss)_raw"    / "Uploaded Duration (hh:mm:ss)_secs"
        "Created Duration (hh:mm:ss)_raw"     / "Created Duration (hh:mm:ss)_secs"
        "Published Duration (hh:mm:ss)_raw"   / "Published Duration (hh:mm:ss)_secs"

    channel_wise_publishing_duration (WIDE — one pair per platform):
        "Facebook Duration_raw"   / "Facebook Duration_secs"
        "Instagram Duration_raw"  / "Instagram Duration_secs"
        "Linkedin Duration_raw"   / "Linkedin Duration_secs"
        "Reels Duration_raw"      / "Reels Duration_secs"
        "Shorts Duration_raw"     / "Shorts Duration_secs"
        "X Duration_raw"          / "X Duration_secs"
        "Youtube Duration_raw"    / "Youtube Duration_secs"
        "Threads Duration_raw"    / "Threads Duration_secs"
"""
    },

    {
        "id": "metric_total_duration_uploaded",
        "type": "metric",
        "tables": ["month_wise_duration",
                   "client_1_combined_data_2025_3_1_2026_2_28",
                   "combined_data_2025_3_1_2026_2_28_by_user"],
        "text": """
Metric: Total Uploaded Duration
Definition:
    Total runtime of all source videos uploaded to Frammer.

Column names:
    month_wise_duration:        "Total Uploaded Duration_secs" / "Total Uploaded Duration_raw"
    combined_data_* tables:     "Uploaded Duration (hh:mm:ss)_secs" / "Uploaded Duration (hh:mm:ss)_raw"

Rules:
    - Use _secs for math and ORDER BY.
    - Use _raw for display in SELECT.
    - To convert to hours: ROUND(col / 3600.0, 2)

Example SQL (uploaded hours by month):
    SELECT "Month",
           "Total Uploaded Duration_raw",
           ROUND("Total Uploaded Duration_secs" / 3600.0, 2) AS uploaded_hours
    FROM month_wise_duration
    ORDER BY uploaded_hours DESC;

Example SQL (uploaded hours by user):
    SELECT "User",
           "Uploaded Duration (hh:mm:ss)_raw",
           ROUND("Uploaded Duration (hh:mm:ss)_secs" / 3600.0, 2) AS uploaded_hours
    FROM combined_data_2025_3_1_2026_2_28_by_user
    ORDER BY uploaded_hours DESC;
"""
    },

    {
        "id": "metric_duration_compression_ratio",
        "type": "metric",
        "tables": ["month_wise_duration"],
        "text": """
Metric: Duration Compression Ratio
Definition:
    Ratio of total CREATED output duration to total UPLOADED source duration.
    Measures how much Frammer condenses source content.

Formula:
    Compression Ratio = "Total Created Duration_secs" / "Total Uploaded Duration_secs"

Interpretation:
    < 1: Outputs are shorter than source (Frammer is summarising/condensing).
         e.g. 0.3 = outputs are 30% the length of source.
    > 1: Outputs are longer than source (unusual).
    = 1: No compression.

Always use NULLIF on the denominator.

Example SQL:
    SELECT "Month",
           "Total Uploaded Duration_raw",
           "Total Created Duration_raw",
           ROUND("Total Created Duration_secs" * 1.0
               / NULLIF("Total Uploaded Duration_secs", 0), 3)
               AS compression_ratio
    FROM month_wise_duration
    ORDER BY "Month";
"""
    },

    {
        "id": "metric_avg_video_duration",
        "type": "metric",
        "tables": ["month_wise_duration", "monthly_chart"],
        "text": """
Metric: Average Video Duration
Definition:
    Average duration per video = total duration in seconds / video count.

Formulas:
    Avg Uploaded Duration  = "Total Uploaded Duration_secs"  / "Total Uploaded"
    Avg Created Duration   = "Total Created Duration_secs"   / "Total Created"
    Avg Published Duration = "Total Published Duration_secs" / "Total Published"

Requires joining month_wise_duration with monthly_chart on "Month".
This is the ONE allowed join between flat summary tables.

Example SQL (avg created duration per video in minutes by month):
    SELECT d."Month",
           ROUND(d."Total Created Duration_secs" * 1.0
               / NULLIF(c."Total Created", 0) / 60.0, 2)
               AS avg_created_duration_mins
    FROM month_wise_duration d
    JOIN monthly_chart c ON d."Month" = c."Month"
    ORDER BY d."Month";
"""
    },

    # ──────────────────────────────────────────────────────────────────
    # RANKING METRICS
    # ──────────────────────────────────────────────────────────────────

    {
        "id": "metric_top_user",
        "type": "metric",
        "tables": ["combined_data_2025_3_1_2026_2_28_by_user",
                   "combined_data_2025_3_1_2026_2_28_by_channel_and_user"],
        "text": """
Metric: Top User / User Leaderboard
Definition:
    Ranking of users by uploaded, created, or published volume.

CRITICAL: User column is named "User" — NOT "Uploaded By".
Count columns: "Uploaded Count", "Created Count", "Published Count"

Dimensions:
    Overall user rank:          combined_data_..._by_user
    User rank within a channel: combined_data_..._by_channel_and_user

Example SQL (full leaderboard by uploads):
    SELECT "User",
           "Uploaded Count",
           "Created Count",
           "Published Count",
           ROUND("Published Count" * 100.0 / NULLIF("Created Count", 0), 2)
               AS publish_rate_pct
    FROM combined_data_2025_3_1_2026_2_28_by_user
    ORDER BY "Uploaded Count" DESC;

Example SQL (top user per channel):
    SELECT "Channel", "User", "Uploaded Count"
    FROM combined_data_2025_3_1_2026_2_28_by_channel_and_user
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY "Channel" ORDER BY "Uploaded Count" DESC
    ) = 1
    ORDER BY "Channel";
"""
    },

    {
        "id": "metric_top_channel",
        "type": "metric",
        "tables": ["channel_wise_publishing",
                   "client_1_combined_data_2025_3_1_2026_2_28",
                   "channel_wise_publishing_duration"],
        "text": """
Metric: Top Channel / Channel Leaderboard
Definition:
    Ranking of channels by publishing volume, creation volume, or duration.

CRITICAL: channel_wise_publishing is WIDE format — no "Total Published" column.
Must SUM all platform columns to get total published per channel:
    "Facebook" + "Instagram" + "Linkedin" + "Reels" + "Shorts"
    + "X" + "Youtube" + "Threads"

For uploaded/created/published counts use client_1_combined_data_...
which has "Uploaded Count", "Created Count", "Published Count" columns.

Example SQL (channels by total published across all platforms):
    SELECT "Channel",
           "Facebook" + "Instagram" + "Linkedin" + "Reels" + "Shorts"
           + "X" + "Youtube" + "Threads" AS total_published
    FROM channel_wise_publishing
    ORDER BY total_published DESC;

Example SQL (channels by uploaded count):
    SELECT "Channel",
           "Uploaded Count",
           "Created Count",
           "Published Count"
    FROM client_1_combined_data_2025_3_1_2026_2_28
    ORDER BY "Uploaded Count" DESC;

Example SQL (channel with most YouTube published hours):
    SELECT "Channel",
           "Youtube Duration_raw",
           ROUND("Youtube Duration_secs" / 3600.0, 2) AS youtube_hours
    FROM channel_wise_publishing_duration
    ORDER BY "Youtube Duration_secs" DESC
    LIMIT 1;
"""
    },

    {
        "id": "metric_peak_month",
        "type": "metric",
        "tables": ["monthly_chart", "month_wise_duration"],
        "text": """
Metric: Peak Month
Definition:
    The month with the highest value for a given metric.

Month label format: 'Mon, YYYY' — e.g. 'Feb, 2026', 'Mar, 2025'.
Always use this exact format in WHERE clauses.

Example SQL (month with highest uploads):
    SELECT "Month", "Total Uploaded"
    FROM monthly_chart
    ORDER BY "Total Uploaded" DESC
    LIMIT 1;

Example SQL (month with highest published duration):
    SELECT "Month",
           "Total Published Duration_raw",
           "Total Published Duration_secs"
    FROM month_wise_duration
    ORDER BY "Total Published Duration_secs" DESC
    LIMIT 1;

Example SQL (month with highest creation multiplier):
    SELECT "Month",
           ROUND("Total Created" * 1.0 / NULLIF("Total Uploaded", 0), 2)
               AS creation_multiplier
    FROM monthly_chart
    ORDER BY creation_multiplier DESC
    LIMIT 1;
"""
    },

]
